// vue3/src/pages/index.vue
<template>
    <div class="test" @click="addCount">index page fdklakdlfjdkalfjdkl fdsa --- {{name}} </div>
    <div>
        <Top />
        <a href="about.html"> to about page </a>
        <img src="../assets/images/507615.png" alt="">
    </div>
</template>

<script lang="ts" setup>
import { ref } from "vue"
import Top from "../components/top.vue"

const name = ref<number>(0);

function addCount(){
    console.log(process.env.NODE_ENV)
    name.value = name.value + 1
}
</script>

<style scoped>
@import "../css/index.css"
</style>

// react/src/pages/main.tsx
import React from "react"
import Top from "../components/top"
import "../css/main.css"
// import img from "../assets/images/507615.png"

export default function Main(){
    return (
        <>
            <div className="top-class">
                <Top content="vans" />
            </div>
            <div className="content-box">
                {/* <img src={img} alt="" /> */}
            </div>
        </>
    )
}
